### ISSUE TITLE
Some problem about  "FeCLAP"

### ISSUE THREAD

**Issue by syajing** [azzeddinetiba/FeCLAP#3]
Hello! I have read your codes of "FeCLAP", it's great! But I couldn't fully understand the codes without the theories. Ror example, which integral mode is applied, how the strain matrix"B" is formed, what the displacement field of this problem is. I am wondering if you could kindly send me the theories about the source program . I promise they will be used only for research purposes.
Thank you very much for your kind consideration and I am looking forward to your early reply.

**Comment by azzeddinetiba** [comment]
Hello, Thank you for bringing this. I did not fully understand your questions though.

- What do you mean by the integral mode ?
- The strain matrix "B" is derived from the spatial derivatives of the shape functions. Unfortunately, I admit that the code is very sloppy and not yet optimized regarding this part.
- By the displacement field, do you mean the degrees of freedom ? if yes the dof considered are the 3 displacements (x, y, z) and two rotations ($\theta_x$, and $\theta_y$) 
- I'm afraid I don't have the references of books I've used to implement the core of the code, but you could find the theory used in any classical mechanics book treating plates bending problems (Zienkiewicz for example).
